detectors:
  TooManyStatements:
    max_statements: 6
  RepeatedConditional:
    max_ifs: 4

directories:
  "db/migrate":
    IrresponsibleModule:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
