development:
  DB_NAME: vodix_development
  DB_USERNAME: rails
  DB_PASSWORD: rails
  DB_HOST: localhost
  HOST: http://35.190.27.31
  SMTP_ADDRESS: smtp.sendgrid.net
  SMTP_DOMAIN: sendgrid.com
  SMTP_USERNAME: HighValueCollaborative
  SMTP_PASSWORD: ^nPQQ6azU6h@
  SECRET_KEY_BASE: 62a8d689db64f229aa2d46fea8f58c95bef2a1c4c8163a31d4b84f9653d7fa48d6f687b876235402004df2fb6b097e6b565e0391f426a05edbbdd4b7102575a2
staging:
  DB_NAME: <%= ENV['DB_NAME'] %>
  DB_USERNAME: <%= ENV['DB_USERNAME'] %>
  DB_PASSWORD: <%= ENV['DB_PASSWORD'] %>
  DB_HOST: <%= ENV['DB_HOST'] %>
  HOST: <%= ENV['HOST'] %>
  SMTP_ADDRESS: <%= ENV['SMTP_ADDRESS'] %>
  SMTP_DOMAIN: <%= ENV['SMTP_DOMAIN'] %>
  SMTP_USERNAME: <%= ENV['SMTP_USERNAME'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  SECRET_KEY_BASE: cefb96a0ff0e55a24d024a54f50c523b9c25786434b1f2f97bd00f71e191b7673046981dce57d2436a53468279aabef87274500ef01d38d6aa9af7b86b0211e7