development:
  DB_NAME: vodix_development
  DB_USERNAME: rails
  DB_PASSWORD: rails
  DB_HOST: localhost
  HOST: http://35.190.27.31
  SMTP_ADDRESS: smtp.sendgrid.net
  SMTP_DOMAIN: sendgrid.com
  SMTP_USERNAME: HighValueCollaborative
  SMTP_PASSWORD: ^nPQQ6azU6h@