# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/front_end
  source_entry_path: packs
  public_output_path: packs

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
    - .mp4
    - .eot
    - .woff
    - .ttf
    - .svg
    - .woff2
    - .woff

development:
  <<: *default

  dev_server:
     https: false
     host: localhost
     port: 3035

test:
  <<: *default

  public_output_path: packs-test

staging:
  <<: *default

production:
  <<: *default

# Note: You must restart bin/webpack-dev-server for changes to take effect
